config/routes.rb
Rails.application.routes.draw do
  get 'main/home'
  get 'main/contacts'
  root 'main#home'
  get 'guitar-buyers-nyc-queens' => 'main#guitars', as: :guitars
  get 'sell-my-bass-nyc-queens' => 'main#basses',  as: :basses  
  get 'sell-my-musical-instruments-equipment-nyc'   => 'main#amps',    as: :amps
  get 'we-buy-pedals-nyc-queens' => 'main#pedals',  as: :pedals
  get 'sell-my-dj-equipment-nyc-queens' => 'main#dj_equipment',  as: :dj_equipment 
  post 'message' => 'main#message', as: :message      
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :create_message_object
    
  def create_message_object 
    @message = Message.new
  end
    
    
  def home
    @title = "Top Rated Musical Instroment Buyers | We Always Pay More"
    @second_title = "Fast, fair, secured way to sell your musical instruments in New York City area. "
    @third_title = "It has never been so ease and conviniant to sell your items in NYC. Call us right now! "
    @description = "We buy all kinds of musicas instruments: guitars, basses, pianos, drums, DJ equipment, we will buy your old ukulele and french horn!"
    @picture = "500_1.jpg"
    render 'template'  
  end

  def contacts
    @title = "Where To Sell Musical Instruments In New York City"
  end
    
  def guitars
    @title = "We Buy Guitars in NYC | You Will Never Find Better Deal"
    @second_title = "Top dollar paid for your musical instrumenst. "
    @third_title = "Best deals in New York City"
    @description = "We buy all kinds of guitars. Electric, acoustic etc. If You want to get best deal, you are on the right page. Call us right now."
    @picture = "500_1.jpg"
    render 'template'  
  end  

  def basses
    @title = "We Buy Basses in New York City"
    @second_title = "We buy Basses and Electric guitars. We always pay more."
    @third_title = "Top rated musical instrument buyers in NYC."
    @description = "If you are looking for the place to sell your bass or any other musical instrument, you just have found the best . Call us right now. Top dollar always paid."
    @picture = "500_1.jpg"
    render 'template'  
  end  
    
  def amps
    @title = "We buy all kind of amplifires in New York City area"
    @second_title = "You will never have better deal. We always pay more."
    @third_title = "Top dollar paid for amplifires in New York."
    @description = "You will never find better deal on your musical instruments. Do not waste your time, call us right now. Top dollar paid for all kind of amplifires in New York."
    @picture = "500_1.jpg"
    render 'template'  
  end 
    
  def pedals
    @title = "We Buy guitar pedals in NYC"
    @second_title = "Top dollar paid for your musical equipment. "
    @third_title = "You will never find better deal, call us right now"
    @description = "If you have any guitar pedals thet you are not using anymore, may be it's the best time to get rid of them. We always pay more."
    @picture = "500_1.jpg"
    render 'template'  
  end 
    
  def dj_equipment
    @title = "Looking for place to sell your DJ equipment? We are here for you."
    @second_title = "We buy all kinds of DJ equipment. Used and New. "
    @third_title = "Top dollar paid for DJ items in New York. Call us right now."
    @description = "We are your best chance to get top cash for your used and new DJ equipment. Do not waste your time, secure your money. We always pay more."
    @picture = "500_1.jpg"
    render 'template'  
  end      
    
  def messages
      render json: Message.all
  end      
    
  def message
      @msg = Message.new({:name => params[:message][:name],
          :email => params[:message][:email],
          :phone_number => params[:message][:phone_number],
          :message => params[:message][:message]})
      @msg.save
     UserMailserMailer.send_mail(@msg.name,
         @msg.email,
         @msg.phone_number,
         @msg.message).deliver_now
     redirect_to root_path  
  end        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/_carousel.html.haml
#myCarousel.carousel.slide{"data-ride" => "carousel"}
  / Indicators
  %ol.carousel-indicators
    %li.active{"data-slide-to" => "0", "data-target" => "#myCarousel"}
    %li{"data-slide-to" => "1", "data-target" => "#myCarousel"}
    %li{"data-slide-to" => "2", "data-target" => "#myCarousel"}
  .carousel-inner{:role => "listbox"}
    .item.active
      %img.first-slide.img-responsive.hidden-xs{:alt => "First slide", :src => "/carousel_1.jpg"}
      %img.second-slide.img-responsive.visible-xs{:alt => "Second slide", :src => "/500_1.jpg"}
      .container
        .carousel-caption
          %h1 We buy all musical instruments and equipment in NYC.
          %p
            Call or text us right now for more info. If you are looking to get top dollar for your items, you are on the right page.
    .item
      %img.second-slide.img-responsive.hidden-xs{:alt => "Second slide", :src => "/carousel_2.jpg"}
      %img.second-slide.img-responsive.visible-xs{:alt => "Second slide", :src => "/500_4.jpg"}
      .container
        .carousel-caption
          %h1 We buy electric guitars and basses in New York City.
          %p
            We know everything about electric guitars and basses. So just bring one you want to sell and get your best deal.
            Cash on the spot.
    .item
      %img.third-slide.img-responsive.hidden-xs{:alt => "Third slide", :src => "/carousel_3.jpg"}
      %img.second-slide.img-responsive.visible-xs{:alt => "Second slide", :src => "/500_3.jpg"}
      .container
        .carousel-caption
          %h1 We buy all kinds of musical instruments and equipment.
          %p
            We always pay more. Do not waste your time, call us right now.
  %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel", :role => "button"}
    %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
    %span.sr-only Previous
  %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel", :role => "button"}
    %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
    %span.sr-only Next
    / /.carousel
    
.container
  .row.toolbar-wrapper-xs
    %a{:href => "tel:7188461600", :role => "button"}
      %i.fa.fa-phone
    %i.fa.fa-comments#btn-send-message
    %a{:href => "javaScript:void(0);", :id => "contacts-toolbar-item"}
      %i.fa.fa-map-marker
      

app/views/layouts/_footer.html.haml
%footer.footer-distributed
  .footer-left
    %h3
      Sell
      %span Guitars
      NYC
    %p.footer-links
      = link_to "Home", root_path
      ·
      =link_to "Guitars", guitars_path
      ·
      = link_to "Basses", basses_path
      ·
      = link_to "AMPs", amps_path
      ·
      = link_to 'Pedals', pedals_path
      ·
      %a{:href => "#"} Contact
    %p.footer-company-name WeBuyGoods.Com © 2016
  .footer-center
    %div
      %i.fa.fa-map-marker
      %p
        %a{:href => "https://www.google.com/maps/dir/Current+Location/8710+Lefferts+BLVD+Richmond+Hill+NY+11418"}
          %span Queens: 8710 Lefferts BLVD
          Richmond Hill, NY, 11418
    %div
      %i.fa.fa-phone
      %p
        %a{:href => "tel:+1-718-846-1600"} +1 (718) 846-1600
    %div
      %i.fa.fa-envelope
      %p
        %a{:href => "mailto:webuygoodsny@gmail.com"} webuygoodsny@gmail.com
  .footer-right
    %p.footer-company-about
      %span We buy Musical Instruments and Equipment in New York City
      We have best customer service and always pay more, so if You have something to sell - we are Your best choice.
    .footer-icons
      %a{:href => "https://www.facebook.com/webuygoodsnyc"}
        %i.fa.fa-facebook
      %a{:href => "https://plus.google.com/106507584776418285314/about"}
        %i.fa.fa-google-plus
      %a{:href => "https://www.instagram.com/webuygoodsnyc/"}
        %i.fa.fa-instagram
      %a{:href => "https://twitter.com/webuygoodsnyc"}
        %i.fa.fa-twitter

app/views/layouts/_navbar.html.haml
.navbar-wrapper
  .container
    %nav.navbar.navbar-inverse.navbar-static-top
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#"} SellMyGuitarNYC.com
        #navbar.navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li
              = link_to "Home", root_path
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                We Buy
                %span.caret
              %ul.dropdown-menu
                %li
                  = link_to 'Guitars', guitars_path
                %li
                  = link_to "Basses", basses_path
                %li
                  = link_to "AMPs", amps_path
                %li
                  = link_to "Pedals", pedals_path
                %li
                  = link_to "DJ Equipment", dj_equipment_path
            %li
              %a{:href => "javaScript:void(0);", :id => "contacts-btn"} Contacts
          %ul.nav.navbar-nav.navbar-right
            %li
              %a{:href => "https://www.facebook.com/webuygoodsnyc"}
                = fa_icon "facebook", class: "fa-lg"
                %span.hidden-sm.hidden-md.hidden-lg
                  = "Facebook" 
            %li
              %a{:href => "https://www.instagram.com/webuygoodsnyc/"}
                = fa_icon "instagram", class: "fa-lg"
                %span.hidden-sm.hidden-md.hidden-lg
                  = "Instagrem"
            %li
              %a{:href => "https://twitter.com/webuygoodsnyc"}
                = fa_icon "twitter", class: "fa-lg"
                %span.hidden-sm.hidden-md.hidden-lg
                  = "Twitter"
            %li
              %a{:href => "https://plus.google.com/106507584776418285314"}
                = fa_icon "google-plus", class: "fa-lg"
                %span.hidden-sm.hidden-md.hidden-lg
                  = "Google Plus"
#location-wrapper
  %a{:href => 'javaScript:void(0);', :class => "btn btn-info", :id => 'btn-close-contacts'}
    = "Close (X)"
  .text-center.col-lg-10.col-lg-offset-1
    .wrapper
      %h2 Contscts:
      %h5 tel: +1 (718) 846-1600
      %h5 email: webuygoodsny@gmail.com
      %hr
      .col-lg-6.col-md-6.col-sm-6.col-xs-12
        %h3 Queens Location #1
        %p
          %iframe{:width=>"100%", :height=>"250" ,:frameborder=>"0" ,:style=>"border:0", :src=>"https://www.google.com/maps/embed/v1/place?q=119-16%20Jamaica%20Ave%20Queens%2C%20New%20York%2C%20NY%2C%20United%20States&key=AIzaSyAG1JHhDDpKIublp2o1A107YHnRFEGQa7E"}
      .col-lg-6.col-md-6.col-sm-6.col-xs-12
        %h3 Queens Location #2
        %p
          %iframe{:width=>"100%", :height=>"250", :frameborder=>"0" ,:style=>"border:0", :src=>"https://www.google.com/maps/embed/v1/place?q=8710%20Lefferts%20Blvd%2C%20Richmond%20Hill%2C%20NY%2C%20United%20States&key=AIzaSyAG1JHhDDpKIublp2o1A107YHnRFEGQa7E"}
      %h3 We are open every day from 10 am till 6 pm      
#message-interupter                  
#message-dialog-wrapper
  %h1.title Ask Question
  .col-lg-10.col-lg-offset-1
    = form_for @message, url: message_path do |f|
      .form-group
        = f.label :name
        = f.text_field :name,class: "form-control"
        %br
        = f.label :email
        = f.text_field :email,class: "form-control"
        %br
        = f.label :phone_number
        = f.text_field :phone_number ,class: "form-control"
        %br
        = f.label :message
        = f.text_area :message ,class: "form-control"
        %br
        = f.button 'Send' , class: 'btn btn-success' , type: :submit

app/views/layouts/_stuff.html.haml
/
  Marketing messaging and featurettes
  \==================================================
/ Wrap the rest of the page in another container to center all the content.
.container.marketing
  / Three columns of text below the carousel
  .row
    .col-lg-4.col-sm-4
      %img.img-circle{:alt => "Generic placeholder image", :height => "140", :src => "/security.png", :width => "140"}/
      %h2 Security
      %p Our shop located in nice neighborhood and we provide all paperwork. (No online creepy strangers in scary places).
    / /.col-lg-4
    .col-lg-4.col-sm-4
      %img.img-circle{:alt => "Generic placeholder image", :height => "140", :src => "/dollar.png", :width => "140"}/
      %h2 We Always Pay More!
      %p Instant cash on the spot. Dont waste you time, call us right now and take your best deal.
    / /.col-lg-4
    .col-lg-4.col-sm-4
      %img.img-square{:alt => "Generic placeholder image", :height => "140", :src => "/calendar.svg", :width => "140"}/
      %h2 Sell On Consignment
      %p If you have time to wait and want to get more money for your goods, we provide consignment.
  / /.col-lg-4
  / /.row
  / START THE FEATURETTES

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title
      = @title
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navbar'
    = render 'layouts/carousel'
    = render 'layouts/stuff'
    = yield
    %br
    = render 'layouts/footer'

app/views/main/contacts.html.haml
<h1>Main#contacts</h1>
<p>Find me in app/views/main/contacts.html.erb</p>

app/views/main/home.html.haml
.container
  .row
    %hr.featurette-divider
      .row.featurette
        .col-md-7
          %h2.featurette-heading
            First featurette heading.
            %span.text-muted It'll blow your mind.
          %p.lead Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
        .col-md-5
          %img.featurette-image.img-responsive.center-block{:alt => "Generic placeholder image", "src" => "/500_#{(Random.new.rand(4) + 1).to_s}.jpg"}/ 
    %hr.featurette-divider  
      .row.featurette
        .col-lg-10.col-md-10.col-sm-10.col-xs-12.col-sm-offset-1.col-md-offset-1.col-lg-offset-1
          %h2 We Buy: 
          %br
          .col-md-4.col-lg-4.col-sm-4.col-xs-6.image-grid
            =image_tag "/1.jpg", :class => "img-responsive"
            %br 
            %h5 All kind of guitars in NYC
          .col-md-4.col-lg-4.col-sm-4.col-xs-6.image-grid
            =image_tag "/4.jpg", :class => "img-responsive"
            %br   
            %h5 Custom musical instruments
          .col-md-4.col-lg-4.col-sm-4.col-xs-6.image-grid
            =image_tag "/3.jpg", :class => "img-responsive"
            %br   
            %h5 All bass guitars, acoustic and electric.
          .col-md-4.col-lg-4.col-sm-4.col-xs-6.image-grid
            =image_tag "/2.jpg", :class => "img-responsive"
            %br   
            %h5 Gibson, Fender and all other amps
          .col-md-4.col-lg-4.col-sm-4.col-xs-6.image-grid
            =image_tag "/5.jpg", :class => "img-responsive"
            %br   
            %h5 Stock and custom pedal boards and pedals 
          .col-md-4.col-lg-4.col-sm-4.col-xs-6.image-grid
            =image_tag "/6.jpg", :class => "img-responsive"
            %br   
            %h5 Saxophones and others

app/views/main/template.html.haml
.container
  .row
    %hr.featurette-divider
      .row.featurette
        .col-md-7
          %h2.featurette-heading.content-wrapper
            = @second_title
            %span.text-muted.content-wrapper 
              = @third_title
          %p.lead.content-wrapper
            = @description
        .col-md-5
          %img.featurette-image.img-responsive.center-block{:alt => "Generic placeholder image", "src" => "#{@picture}"}/ 
    %hr.featurette-divider  
      .row.featurette
        .col-lg-10.col-md-10.col-sm-10.col-xs-12.col-sm-offset-1.col-md-offset-1.col-lg-offset-1
          %br
          .col-md-4.col-lg-4.col-sm-4.col-xs-6.image-grid
            =image_tag "/1.jpg", :class => "img-responsive"
            %br 
            %h5 All kinds of guitars in NYC
          .col-md-4.col-lg-4.col-sm-4.col-xs-6.image-grid
            =image_tag "/4.jpg", :class => "img-responsive"
            %br   
            %h5 Custom musical instruments
          .col-md-4.col-lg-4.col-sm-4.col-xs-6.image-grid
            =image_tag "/3.jpg", :class => "img-responsive"
            %br   
            %h5 All bass guitars, acoustic and electric.
          .col-md-4.col-lg-4.col-sm-4.col-xs-6.image-grid
            =image_tag "/2.jpg", :class => "img-responsive"
            %br   
            %h5 Gibson, Fender and all other amps
          .col-md-4.col-lg-4.col-sm-4.col-xs-6.image-grid
            =image_tag "/5.jpg", :class => "img-responsive"
            %br   
            %h5 Boards, processors and pedals 
          .col-md-4.col-lg-4.col-sm-4.col-xs-6.image-grid
            =image_tag "/6.jpg", :class => "img-responsive"
            %br   
            %h5 
              = "Saxophones, ukuleles and french horns ;)"